# Generated by Django 5.2 on 2025-10-10 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة'),
        ),
        migrations.AddField(
            model_name='store',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'في انتظار الموافقة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الموافقة'),
        ),
        migrations.AddField(
            model_name='store',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stores', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة'),
        ),
        migrations.AddField(
            model_name='store',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'store_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='صاحب المتجر'),
        ),
    ]
