# Generated by Django 5.2 on 2025-10-10 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_store_approval_date_store_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'store_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='صاحب المتجر'),
        ),
    ]
