# Generated by Django 5.2 on 2025-08-22 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_store_name_alter_store_owner_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='store',
            name='unique_store_name_per_owner',
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المتجر'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(limit_choices_to={'user_type': 'store_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='صاحب المتجر'),
        ),
    ]
