# Generated by Django 5.2 on 2025-10-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_alter_category_store_alter_product_store'),
        ('users', '0004_alter_store_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
