# Generated by Django 5.2 on 2025-10-17 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المتجر')),
                ('description', models.TextField(verbose_name='وصف المتجر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/', verbose_name='شعار المتجر')),
                ('address', models.TextField(verbose_name='عنوان المتجر')),
                ('phone', models.CharField(max_length=15, verbose_name='هاتف المتجر')),
                ('email', models.EmailField(max_length=254, verbose_name='بريد المتجر الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='موقع المتجر')),
                ('approval_status', models.CharField(choices=[('pending', 'في انتظار الموافقة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الموافقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_verified', models.BooleanField(default=False, verbose_name='متحقق منه')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stores', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'store_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='صاحب المتجر')),
            ],
            options={
                'verbose_name': 'متجر',
                'verbose_name_plural': 'المتاجر',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='stores.store', verbose_name='المتجر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store', verbose_name='المتجر'),
        ),
    ]
