# Generated by Django 5.2 on 2025-12-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_favoritestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, help_text='المقاس المختار', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='size',
            field=models.CharField(blank=True, help_text='المقاس المباع', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size')},
        ),
        migrations.CreateModel(
            name='ProductSizeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='مثال: S, M, L, XL, XXL', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0, help_text='الكمية المتاحة لهذا المقاس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='stores.product')),
            ],
            options={
                'verbose_name': 'كمية المقاس',
                'verbose_name_plural': 'كميات المقاسات',
                'unique_together': {('product', 'size')},
            },
        ),
    ]
