# Generated by Django 5.2 on 2026-02-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_cartitem_size_sale_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='السعر الأصلي قبل الخصم - عند تعبئته يظهر المنتج في العروض', max_digits=10, null=True),
        ),
    ]
